#!/usr/bin/python3

import egtlib
import argparse
import sys
import logging

VERSION = "0.1"

def main():
    parser = argparse.ArgumentParser(description="Enrico's getting things done")
    parser.add_argument("--version", action="version", version="%(prog)s " + VERSION)
    parser.add_argument("--verbose", "-v", action="store_true", help="verbose output")
    parser.add_argument("--debug", action="store_true", help="debug output")
    parser.add_argument("--archived", action="store_true", help="also show archived projects")
    # self.settings.string(['backup-output'], "backup tarball to generate (by default it is sent to stdout) (the filename is passed to strftime, so you can use something like %Y-%m-%d in the configuration)", metavar="filename")
    # self.settings.boolean(['vcal'], "output events in vCalendar format")
    subparsers = parser.add_subparsers(help="egt subcommands")

    from egtlib.commands import Command, CommandError

    for c in Command.COMMANDS:
        name = getattr(c, "NAME", c.__name__.lower())
        cmd = subparsers.add_parser(name, help=c.__doc__)
        cmd.set_defaults(command=c)
        c.add_args(cmd)

    args = parser.parse_args()

    # Setup logging
    FORMAT = "%(asctime)-15s %(levelname)s %(message)s"
    if args.debug:
        logging.basicConfig(level=logging.DEBUG, stream=sys.stderr, format=FORMAT)
    elif args.verbose:
        logging.basicConfig(level=logging.INFO, stream=sys.stderr, format=FORMAT)
    else:
        logging.basicConfig(level=logging.WARN, stream=sys.stderr, format=FORMAT)

    if args.command:
        action = args.command(args)
        try:
            action.main()
        except CommandError as e:
            print(e, file=sys.stderr)
            sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()

