#!/usr/bin/python3
import argparse
import sys

VERSION = "0.4"


def main():
    parser = argparse.ArgumentParser(description="Enrico's getting things done")
    parser.add_argument("--version", action="version", version="%(prog)s " + VERSION)
    parser.add_argument("--verbose", "-v", action="store_true", help="verbose output")
    parser.add_argument("--debug", action="store_true", help="debug output")
    subparsers = parser.add_subparsers(help="egt subcommands", required=True, dest="command")

    from egtlib.commands import COMMANDS
    from egtlib.cli import Fail

    for c in COMMANDS:
        c.add_subparser(subparsers)

    args = parser.parse_args()
    cmd = args.command(args)

    try:
        return cmd.main()
    except Fail as e:
        print(e, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
