#!/usr/bin/python
import cliapp
import egtlib
import datetime

VERSION="0.1"

class EgtApp(cliapp.Application):
    def __init__(self):
        super(EgtApp, self).__init__(
            progname="egt",
            version=VERSION,
            description="Enrico's Getting Things Done",
        )

    def add_settings(self):
        self.settings.string(['tag', 't'], "limit processing to projects with the given (comma separated) tag(s)", metavar="tag")

    def make_egt(self):
        if self.settings["tag"]:
            return egtlib.Egt(tags=self.settings["tag"].split(","))
        else:
            return egtlib.Egt()

    def cmd_scan(self, args):
        """
        Update the list of known project files, by scanning everything below
        the home directory.
        """
        e = self.make_egt()
        e.scan()

    def cmd_list(self, args):
        """
        List known projects.
        """
        e = self.make_egt()
        for k, v in e.state.projects.iteritems():
            print "%s\t%s" % (v.name, v.path)

    def cmd_summary(self, args):
        e = self.make_egt()
        if args:
            projs = (e.project(a) for a in args)
        else:
            projs = e.projects.itervalues()

        blanks = []
        worked = []
        for p in projs:
            if p.last_updated is None:
                blanks.append(p)
            else:
                worked.append(p)

        blanks.sort(key=lambda p:p.name)
        worked.sort(key=lambda p:p.last_updated)

        for p in blanks: p.summary()
        for p in worked: p.summary()

    def cmd_term(self, args):
        """
        Open a terminal in a project directory.
        """
        e = self.make_egt()
        for name in args:
            proj = e.project_by_name(name)
            proj.spawn_terminal()

    def cmd_work(self, args):
        """
        Open a terminal in a project directory, and edit the project file.
        """
        e = self.make_egt()
        for name in args:
            proj = e.project_by_name(name)
            proj.spawn_terminal(with_editor=True)

    def cmd_edit(self, args):
        """
        Open a terminal in a project directory, and edit the project file.
        """
        e = self.make_egt()
        for name in args:
            proj = e.project_by_name(name)
            proj.run_editor()

    def cmd_weekrpt(self, args):
        """
        Compute weekly reports
        """
        e = self.make_egt()
        if args:
            end = datetime.datetime.strptime(args[0], "%Y-%m-%d").date()
        else:
            end = None
        rep = e.weekrpt(end=end)
        print "Activity from %s to %s:" % (rep["begin"], rep["until"])
        print "%d entries, %d hours in total, %d hours per day, %d hours per working day" % (
            rep["count"], rep["hours"], rep["hours_per_day"], rep["hours_per_workday"])
        for l, p in rep["log"]:
            l.output(p.name)

    def cmd_serve(self, args):
        """
        Start a web server for reports
        """
        from egtlib import web
        print "Server starting at localhost:5000"
        web.app.make_egt = self.make_egt
        web.app.debug = True
        web.app.run()

if __name__ == '__main__':
    EgtApp().run()

