from typing import List, Optional


class TaskWarrior:
    def __init__(self, marshal: bool = True, **kw): ...
    def filter_tasks(self, filter: dict): ...
    def get_task(self, id: int): ...
    def task_add(self, description: str, tags: Optional[List[str]] = None, **kw): ...
    def task_done(self, **kw): ...
